version: '3.8'  # 最新のバージョンを使用

services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: darttripdb
      MYSQL_USER: develop
      MYSQL_PASSWORD: develop
      TZ: Asia/Tokyo
    # ports:
      # - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: darttrip-backend:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/darttripdb?useSSL=false&serverTimezone=Asia/Tokyo&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: develop
      SPRING_DATASOURCE_PASSWORD: develop
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      TZ: Asia/Tokyo
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: darttrip-frontend:latest
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8080/api
    depends_on:
      - backend

volumes:
  db-data:
